# Generated by Django 2.0 on 2019-06-28 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('email', models.CharField(max_length=25, verbose_name='email')),
                ('hob', models.CharField(max_length=250, verbose_name='hob')),
                ('gender', models.CharField(max_length=15, verbose_name='gender')),
                ('dob', models.DateTimeField(verbose_name='dob')),
                ('add', models.CharField(max_length=250, verbose_name='add')),
                ('school_inter', models.CharField(max_length=100, verbose_name='school_inter')),
                ('inter', models.CharField(max_length=25, verbose_name='inter')),
                ('board_inter', models.CharField(max_length=25, verbose_name='board_inter')),
                ('year_inter', models.DateTimeField(verbose_name='year_inter')),
                ('high', models.CharField(max_length=25, verbose_name='high')),
                ('school_high', models.CharField(max_length=100, verbose_name='school_high')),
                ('board_high', models.CharField(max_length=25, verbose_name='board_high')),
                ('year_high', models.DateTimeField(verbose_name='year_high')),
                ('ug', models.CharField(max_length=15, verbose_name='ug')),
                ('ug_coll', models.CharField(max_length=50, verbose_name='ug_coll')),
                ('year_ug', models.DateTimeField(verbose_name='year_ug')),
                ('skill', models.CharField(max_length=150, verbose_name='skill')),
                ('area_of_skill', models.CharField(max_length=25, verbose_name='area_of_skill')),
                ('exp', models.CharField(max_length=15, verbose_name='exp')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted on')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author ')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Upload_resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='', verbose_name='resume')),
                ('Upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted on')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author ')),
            ],
            options={
                'ordering': ['-Upload_date'],
            },
        ),
    ]
